name: Build C Project

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up MSVC (Windows only)
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Compile (Windows)
        if: runner.os == 'Windows'
        run: |
          cl /nologo /W4 /Fe:main.exe /std:c89 /Ilibs 02\main.c libs\*.c

      - name: Compile (macOS)
        if: runner.os == 'macOS'
        run: |
          clang -Wall -Wextra -std=c89 -Ilibs 02/main.c libs/*.c -o main
